import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme-provider"
import { Toaster } from "@/components/ui/toaster"
import { Providers } from "@/providers";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";

import { cn } from "@/lib/utils"
import { ModeToggle } from './../components/ui/theme-toggle';
import Sidebar from "@/components/sidebar/Sidebar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body suppressHydrationWarning className={cn(
        "h-screen w-screen flex overflow-hidden bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers  >
            <>
              <aside>
                <Sidebar />
              </aside>
              <main className="w-full bg-background bg-opacity-20 overflow-y-auto">
                {children}
              </main>
              <Toaster />
              <div className="absolute bottom-2 right-2">
                <ModeToggle />
              </div>
            </>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
